const data = [
  [
    {
      id: 1,
      runId: 245,
      runName: 'Load Files',
      status: 'Executing',
      jobId: 0,
      createDate: '8/13/2021',
    },
    {
      id: 1,
      runId: 245,
      runName: 'Load Files',
      status: 'Executing',
      jobId: 1,
      createDate: '8/13/2021',
    },
    {
      id: 1,
      runId: 245,
      runName: 'Load Files',
      status: 'processed',
      jobId: 2,
      createDate: '8/13/2021',
    },
    {
      id: 1,
      runId: 245,
      runName: 'Load Files',
      status: 'Executing',
      jobId: 3,
      createDate: '8/13/2021',
    },
  ],
  [
    {
      id: 2,
      runId: 246,
      runName: 'Load Files',
      status: 'Executing',
      jobId: 0,
      createDate: '8/13/2021',
    },
    {
      id: 2,
      runId: 246,
      runName: 'Load Files',
      status: 'Executing',
      jobId: 1,
      createDate: '8/13/2021',
    },
    {
      id: 2,
      runId: 246,
      runName: 'Load Files',
      status: 'Executing',
      jobId: 2,
      createDate: '8/13/2021',
    },
    {
      id: 2,
      runId: 245,
      runName: 'Load Files',
      status: 'Executing',
      jobId: 3,
      createDate: '8/13/2021',
    },
  ],
  [
    {
      id: 3,
      runId: 247,
      runName: 'Load Files',
      status: 'Failed',
      jobId: 0,
      createDate: '8/13/2021',
    },
    {
      id: 3,
      runId: 247,
      runName: 'Load Files',
      status: 'Executing',
      jobId: 1,
      createDate: '8/13/2021',
    },
    {
      id: 3,
      runId: 247,
      runName: 'Load Files',
      status: 'processed',
      jobId: 2,
      createDate: '8/13/2021',
    },
    {
      id: 3,
      runId: 245,
      runName: 'Load Files',
      status: 'processed',
      jobId: 3,
      createDate: '8/13/2021',
    },
  ],
];

export default data;
